### ISSUE TITLE
img

### ISSUE THREAD

**Issue by internationalwe** [boostcampaitech6/level1-imageclassification-cv-09#3]

**Comment by internationalwe** [comment]
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/b9420f93-2d71-4868-98dc-fab4230327ce)
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/e568e14f-9f86-4c0d-95b5-2c1e0651548b)

**Comment by internationalwe** [comment]
![대회2등우리팀사진](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/c3544348-9eba-495f-b38c-0900559f8c36)

**Comment by internationalwe** [comment]
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/b52efa91-7ce2-4b45-8f23-171b493cb0d5)
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/c743d3ad-6a23-4260-abb8-149f3789d728)
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/cee82b7c-bf22-403e-9843-f9e84e692fe6)

**Comment by internationalwe** [comment]
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/dc7469e0-5a90-489f-905f-019d77168940)
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/de7d2130-2836-430e-b0ea-d91ed2251d9a)

**Comment by minyun-e** [comment]
![base_attentionMap](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/7cab28bd-d9d5-4402-bd23-4728391245f0)

**Comment by minyun-e** [comment]
![Midjourney_bg_am](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/f31c9575-baa2-4baf-84d3-a88a297505e7)

**Comment by minyun-e** [comment]
![Midjourney_bg_faceDetection_am](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/621f42f0-a422-4fcd-8e0d-d06b0efc7e16)

**Comment by minyun-e** [comment]
<img width="638" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/26fe96da-56e4-4877-9a3f-e916dab67d16">

**Comment by minyun-e** [comment]
<img width="629" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/a0275cc1-4524-4836-80ad-aaf6ca3f9c83">

**Comment by minyun-e** [comment]
<img width="845" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/b0f5cb04-60e0-4fab-91c5-035ecbd4b605">

**Comment by minyun-e** [comment]
<img width="845" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/adbfea93-cfaa-44bd-9afc-78f1e2099416">

**Comment by minyun-e** [comment]
<img width="622" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/15854c60-373d-42ff-b778-854577e223be">

**Comment by minyun-e** [comment]
<img width="1050" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/bea72ac2-adb3-491a-be13-4b918c9cf09b">

**Comment by minyun-e** [comment]
<img width="332" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/cdbc3e36-9685-4be9-b056-e1c9831bfdbe">

**Comment by minyun-e** [comment]
<img width="1290" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/d05091cd-5d0f-4057-b309-27574587d2a0">

**Comment by minyun-e** [comment]
<img width="398" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/8bb62be0-cee5-49fb-9496-6e2a9f14a048">

**Comment by minyun-e** [comment]
<img width="1860" alt="Untitled-1" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/81c3321d-d5e9-4405-a12f-1ecdc7243a75">

**Comment by minyun-e** [comment]
<img width="812" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/6eb9cf43-0e1a-441f-9799-6844b66bf5e4">

**Comment by minyun-e** [comment]
<img width="809" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/fca65e66-e3f1-48c1-947e-8943da342aab">

**Comment by minyun-e** [comment]
<img width="807" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/d0225e58-bee2-4986-a0f9-d88a66095ca0">

**Comment by minyun-e** [comment]
<img width="805" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/5155cd91-fe3d-46dc-bab4-8a94a442422d">

**Comment by minyun-e** [comment]
<img width="1190" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/76c939c5-f327-4889-bb3c-03d3a6f68608">

**Comment by minyun-e** [comment]
<img width="717" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/d2ffd801-091f-4939-b298-d62c9ef6ba84">

**Comment by minyun-e** [comment]
<img width="1074" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/717976ee-9976-4a3e-8b9e-d30550536272">

**Comment by minyun-e** [comment]
<img width="1116" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/11bf152f-6d03-4778-adbb-5fcc88b5d4e7">

**Comment by internationalwe** [comment]
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/20a6dcbd-adf9-42aa-9f4f-97930f3e9b48)
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/46400961/e785eaeb-cf53-4984-a194-608778f67951)

**Comment by minyun-e** [comment]
<img width="914" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/9ea51ee5-e2be-4cf4-87bf-4807ef208cc0">

**Comment by minyun-e** [comment]
<img width="1008" alt="image" src="https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/e1200a6c-d3df-4ad7-a14a-c9f9463b57f1">

**Comment by minyun-e** [comment]
![image](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/4f6d10f9-5de1-4b9c-b10f-be0839f31e18)

**Comment by minyun-e** [comment]
![훈이](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/d003599f-4092-41e2-ba01-c7e5153f5655)

**Comment by minyun-e** [comment]
![짱구](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/be823de7-bf3d-4e37-9789-9592f8d2259d)

**Comment by minyun-e** [comment]
![맹구](https://github.com/boostcampaitech6/level1-imageclassification-cv-09/assets/136993865/c181bf23-c6a6-42b3-8ec6-415b6ebbf5dc)
